import { useEffect, useState } from 'react'
import { Flag, Gift, MessageCircle, Send, ShieldCheck, UserPlus, X } from 'lucide-react'

export type Person={id:number;name:string;avatar:string;username:string;online:boolean}
export type ChatMessage={id:number;name:string;text:string;time:string;own:boolean}
const people:Person[]=[{id:1,name:'Андрей',avatar:'👨🏻',username:'andrey',online:true},{id:2,name:'Мария',avatar:'👩🏻',username:'maria',online:true},{id:3,name:'Сергей',avatar:'👨🏼',username:'sergey',online:false},{id:4,name:'Алина',avatar:'👩🏻',username:'alina',online:true}]
const initialMessages:ChatMessage[]=[{id:1,name:'Андрей',text:'Кто сегодня гуляет?',time:'21:34',own:false},{id:2,name:'Мария',text:'Я после девяти могу 🙂',time:'21:35',own:false},{id:3,name:'Ты',text:'Всем привет!',time:'21:36',own:true},{id:4,name:'Сергей',text:'Я тоже за 👍',time:'21:37',own:false}]
export function Modal({title,kicker,onClose,children}:{title:string;kicker?:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><div>{kicker&&<span className="section-kicker">{kicker}</span>}<h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={19}/></button></div>{children}</div></div>}
export function GiftModal({balance,onClose,onSend}:{balance:number;onClose:()=>void;onSend:(price:number,gift:string,person:string)=>void}){const [person,setPerson]=useState('Андрей');const [gift,setGift]=useState('❤️');const gifts=[['❤️','Сердце',25],['🌹','Роза',50],['💎','Алмаз',100],['🎁','Подарок',150],['🔥','Огонь',200],['👑','Корона',500]] as const;const current=gifts.find(x=>x[0]===gift)??gifts[0];return <Modal title="Подарки" kicker="ПОДАРКИ · NURCOIN" onClose={onClose}><div className="gift-balance"><div><span>Твой баланс</span><strong>{balance.toLocaleString('ru-RU')} NC</strong></div><Gift size={23}/></div><span className="section-kicker">Кому отправить</span><div className="feature-modal-list gift-people">{people.map(p=><button key={p.id} className={person===p.name?'selected':''} onClick={()=>setPerson(p.name)}><span className="feature-avatar">{p.avatar}</span><div><b>{p.name}</b><span>{p.online?'онлайн':'недавно'}</span></div></button>)}</div><span className="section-kicker">Выбери подарок</span><div className="gift-catalog">{gifts.map(([emoji,label,cost])=><button key={emoji} className={gift===emoji?'selected':''} onClick={()=>setGift(emoji)}><strong>{emoji}</strong><b>{label}</b><span>{cost} NC</span></button>)}</div><div className="gift-purchase-row"><span>Стоимость</span><strong>{current[2]} NC</strong></div><button className="primary-button" disabled={balance<current[2]} onClick={()=>onSend(current[2],gift,person)}>{balance<current[2]?'Недостаточно NC':'Отправить '+gift+' · '+current[2]+' NC'}</button></Modal>}

export function ChatRoom({title='Общий чат',onBack,onGift,onNotify,onOpenProfile}:{title?:string;onBack:()=>void;onGift:()=>void;onNotify?:(title:string,text:string)=>void;onOpenProfile?:(person:Person)=>void}){const [message,setMessage]=useState('');const [messages,setMessages]=useState(initialMessages);const [reported,setReported]=useState(false);useEffect(()=>{const timer=setInterval(()=>setMessages(v=>[...v,{id:Date.now(),name:'Денис',text:'Кто ещё здесь? 👋',time:'сейчас',own:false}].slice(-20)),9000);return()=>clearInterval(timer)},[]);const send=()=>{const value=message.trim();if(!value)return;setMessages(v=>[...v,{id:Date.now(),name:'Ты',text:value,time:'сейчас',own:true}]);setMessage('')};const report=()=>{setReported(true);onNotify?.('Жалоба отправлена','Сообщение передано модератору.');setTimeout(()=>setReported(false),2200)};return <section className="chat-screen"><header className="chat-header"><button className="back-button" onClick={onBack}>‹</button><div className="room-avatar room-avatar-small">💬</div><div className="chat-heading"><strong>{title}</strong><span><i/> 247 онлайн</span></div><button className="icon-button" onClick={onGift}><Gift size={18}/></button></header><div className="chat-safety"><ShieldCheck size={14}/><span>Уважай собеседников и не публикуй чужие данные.</span></div><div className="messages">{messages.map(item=><div className={'message-row '+(item.own?'message-own':'')} key={item.id}><button className="message-avatar" onClick={()=>!item.own&&onOpenProfile?.(people.find(p=>p.name===item.name)||people[0])}>{item.name[0]}</button><div className="message-bubble"><div className="message-meta"><strong>{item.name}</strong><span>{item.time}</span></div><p>{item.text}</p><button className="message-report" onClick={report}><Flag size={11}/></button></div></div>)}</div>{reported&&<div className="report-toast">Жалоба отправлена модератору</div>}<div className="composer-wrap"><div className="composer"><button onClick={onGift}><Gift size={19}/></button><button onClick={()=>onNotify?.('Фото','Загрузка фото будет подключена на backend.')}>＋</button><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Написать сообщение..."/><button className="send-button" onClick={send}><Send size={18}/></button></div></div></section>}
export function FriendsPage({friends,onOpenChat,onOpenProfile,onAdd}:{friends:Person[];onOpenChat:(p:Person)=>void;onOpenProfile:(p:Person)=>void;onAdd:()=>void}){return <section><PageTitle title="Друзья" subtitle="Люди, с которыми ты общаешься"/><button className="add-friend-button" onClick={onAdd}><UserPlus size={17}/> Найти людей и добавить в друзья</button><div className="friends-list">{friends.map(p=><button className="friend-row" key={p.id} onClick={()=>onOpenProfile(p)}><span className="friend-avatar">{p.avatar}</span><span className="friend-info"><strong>{p.name}</strong><small>@{p.username} · {p.online?'онлайн':'был(а) недавно'}</small></span><span className="friend-chat" onClick={e=>{e.stopPropagation();onOpenChat(p)}}><MessageCircle size={17}/></span></button>)}</div></section>}
export function PeoplePage({onAdd,onOpenProfile}:{onAdd:(p:Person)=>void;onOpenProfile:(p:Person)=>void}){return <section><PageTitle title="Люди" subtitle="Общайся, добавляй в друзья, отправляй подарки"/><div className="people-list">{people.map(p=><div className="person-row" key={p.id}><button className="person-main" onClick={()=>onOpenProfile(p)}><span className="friend-avatar">{p.avatar}</span><span className="friend-info"><strong>{p.name}</strong><small>@{p.username} · {p.online?'онлайн':'недавно'}</small></span></button><button className="add-mini" onClick={()=>onAdd(p)}><UserPlus size={16}/></button></div>)}</div></section>}
export function PersonModal({person,isFriend,onClose,onAdd,onChat,onGift}:{person:Person;isFriend:boolean;onClose:()=>void;onAdd:()=>void;onChat:()=>void;onGift:()=>void}){return <Modal title={person.name} kicker={person.online?'Сейчас онлайн':'@'+person.username} onClose={onClose}><div className="person-profile"><div className="person-profile-avatar">{person.avatar}</div><h3>{person.name}</h3><span>@{person.username}</span></div><div className="person-actions"><button className="primary-button" onClick={onChat}><MessageCircle size={16}/> Написать</button><button className="secondary-button" onClick={onGift}><Gift size={16}/> Подарок</button>{!isFriend&&<button className="secondary-button" onClick={onAdd}><UserPlus size={16}/> Добавить в друзья</button>}</div><div className="profile-report"><Flag size={14}/> Пожаловаться на пользователя</div></Modal>}
function PageTitle({title,subtitle}:{title:string;subtitle:string}){return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div></div>}
